<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.306">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW8_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW8_files/libs/quarto-html/quarto.js"></script>
<script src="HW8_files/libs/quarto-html/popper.min.js"></script>
<script src="HW8_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW8_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW8_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW8_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW8_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW8_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 8</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First we will load the </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Required Libraries</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in check_dep_version(): ABI version mismatch: 
lme4 was built with Matrix ABI version 1
Current Matrix ABI version is 0
Please re-install lme4 from source or restore original 'Matrix' package</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:faraway':

    logit, vif</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'sandwich' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<section id="question-1-for-the-prostate-data-fit-a-model-with-lpsa-as-the-response-and-the-other-variables-as-predictors." class="level1">
<h1>Question 1: For the prostate data, fit a model with lpsa as the response and the other variables as predictors.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(prostate)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> ., <span class="at">data =</span> prostate)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lpsa ~ ., data = prostate)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.7331 -0.3713 -0.0170  0.4141  1.6381 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.669337   1.296387   0.516  0.60693    
lcavol       0.587022   0.087920   6.677 2.11e-09 ***
lweight      0.454467   0.170012   2.673  0.00896 ** 
age         -0.019637   0.011173  -1.758  0.08229 .  
lbph         0.107054   0.058449   1.832  0.07040 .  
svi          0.766157   0.244309   3.136  0.00233 ** 
lcp         -0.105474   0.091013  -1.159  0.24964    
gleason      0.045142   0.157465   0.287  0.77503    
pgg45        0.004525   0.004421   1.024  0.30886    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7084 on 88 degrees of freedom
Multiple R-squared:  0.6548,    Adjusted R-squared:  0.6234 
F-statistic: 20.86 on 8 and 88 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Interpretations of the Residuals Summary and Model</p>
<ul>
<li><p>The residuals range from a minimum of -1.7331 to a maximum of 1.6381 with the median being -0.0170 and the 1st and 3rd quartiles as -0.3713 and 0.4141, respectively. This indicates that the residuals are centered around zero.</p></li>
<li><p>The intercept is B_0 = 0.669337, indicates that when all other predictors are at zero, the log PSA is 0.669. However, this is not statistically significant as p = 0.60693.</p></li>
<li><p>The B_1 coefficient is 0.587022, indicating that for each unit increase in lcavol, lpsa increases by approximately 0.587 when all other predictors are held constant. This is statistically significant as p = 2.11e-09.</p></li>
<li><p>The B_2 coefficient is 0.454467, indicating that for each unit increase in lweight, lpsa increases by approximately 0.454 when all other predictors are held constant. This is statistically significant as p = 0.00896.</p></li>
<li><p>The B_3 coefficient is -0.019637, indicating that for each unit increase in age, lpsa decreases by approximately 0.020 when all other predictors are held constant. However, this is not statistically significant as p = 0.08229.</p></li>
<li><p>The B_4 coefficient is 0.107054, indicating that for each unit increase in lbph, lpsa increases by approximately 0.107 when all other predictors are held constant. However, this is not statistically significant as p = 0.07040.</p></li>
<li><p>The B_5 coefficient is 0.766157, indicating that for each unit increase in svi, lpsa increases by approximately 0.766 when all other predictors are held constant. This is statistically significant as p = 0.00233.</p></li>
<li><p>The B_6 coefficient is -0.105474, indicating that for each unit increase in lcp, lpsa decreases by approximately 0.105 when all other predictors are held constant. However, this is not statistically significant as p = 0.24964.</p></li>
<li><p>The B_7 coefficient is 0.045142, indicating that for each unit increase in gleason, lpsa increases by approximately 0.045 when all other predictors are held constant. However, this is not statistically significant as p = 0.77503.</p></li>
<li><p>The B_8 coefficient is 0.004525, indicating that for each unit increase in pgg45, lpsa increases by approximately 0.0045 when all other predictors are held constant. However, this is not statistically significant as p = 0.30886.</p></li>
<li><p>The R-squared value which is 0.6548, it indicates that approximately 65.48% of the variability in lpsa is explained by the model.</p></li>
<li><p>The F-statistic is 20.86 with a p-value &lt; 2.2e-16, indicating that the overall model is statistically significant.</p></li>
</ul>
<p>Hence we can say that the significant predictors in the model are lcavol, lweight, and svi.</p>
</section>
<section id="a.-compute-and-comment-on-kappa-and-the-condition-numbers." class="level1">
<h1>1.A. Compute and comment on Kappa and the condition numbers.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(model)[,<span class="sc">-</span><span class="dv">1</span>]  <span class="co"># remove the intercept</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kappa</span>(X) <span class="co">#231.5122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 231.5122</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>eig <span class="ot">&lt;-</span> <span class="fu">eigen</span>(<span class="fu">scale</span>(X, <span class="at">scale =</span> <span class="cn">FALSE</span>) <span class="sc">%*%</span> <span class="fu">t</span>(<span class="fu">scale</span>(X, <span class="at">scale =</span> <span class="cn">FALSE</span>)))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">max</span>(eig<span class="sc">$</span>values)<span class="sc">/</span>eig<span class="sc">$</span>values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in sqrt(max(eig$values)/eig$values): NaNs produced</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1.000000e+00 3.955688e+00 2.014693e+01 2.132123e+01 4.097032e+01
 [6] 5.841681e+01 6.969460e+01 9.775832e+01 4.952803e+07 6.431383e+07
[11] 8.466123e+07 1.335558e+08 1.962182e+08 2.270487e+08 2.287397e+08
[16] 2.315737e+08 2.354806e+08 2.561777e+08 2.899025e+08 3.263348e+08
[21] 3.390835e+08 3.779647e+08 3.829093e+08 3.889158e+08 3.928017e+08
[26] 4.124932e+08 4.204322e+08 4.255745e+08 4.607615e+08 4.973882e+08
[31] 5.083599e+08 5.147257e+08 5.669528e+08 5.756206e+08 6.651276e+08
[36] 7.263821e+08 7.280253e+08 7.980844e+08 8.716025e+08 8.757833e+08
[41] 9.602782e+08 9.868271e+08 1.042014e+09 1.102869e+09 1.136661e+09
[46] 1.312726e+09 1.337908e+09 1.426455e+09 1.566047e+09 1.589966e+09
[51] 1.825586e+09 1.928320e+09 1.937890e+09 2.451107e+09 2.736666e+09
[56] 2.905551e+09 6.201388e+09 7.464110e+09          NaN          NaN
[61]          NaN          NaN          NaN          NaN          NaN
[66]          NaN          NaN          NaN          NaN          NaN
[71]          NaN          NaN          NaN          NaN          NaN
[76]          NaN          NaN          NaN          NaN          NaN
[81]          NaN          NaN          NaN          NaN          NaN
[86]          NaN          NaN          NaN          NaN          NaN
[91]          NaN          NaN          NaN          NaN          NaN
[96]          NaN          NaN</code></pre>
</div>
</div>
<p>The value of Kappa is 231.5122 which is higher than the K <span class="math inline">\(\ge\)</span> 30 threshold. This indicates that there could be problematic collinearity in model 1 among the predictors in the model. The condition numbers have a wide range between 1.00 and 7.46e+09 which supports the observation that there is problematic collinearity.</p>
</section>
<section id="b.-compute-and-comment-on-the-correlations-between-the-predictors.-round-to-3-decimal-places." class="level1">
<h1>1.B. Compute and comment on the correlations between the predictors. Round to 3 decimal places.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">cor</span>(prostate[,<span class="sc">-</span><span class="dv">9</span>]), <span class="dv">3</span>)  <span class="co"># excluding lpsa</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>cor_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        lcavol lweight   age   lbph    svi    lcp gleason pgg45
lcavol   1.000   0.194 0.225  0.027  0.539  0.675   0.432 0.434
lweight  0.194   1.000 0.308  0.435  0.109  0.100  -0.001 0.051
age      0.225   0.308 1.000  0.350  0.118  0.128   0.269 0.276
lbph     0.027   0.435 0.350  1.000 -0.086 -0.007   0.078 0.078
svi      0.539   0.109 0.118 -0.086  1.000  0.673   0.320 0.458
lcp      0.675   0.100 0.128 -0.007  0.673  1.000   0.515 0.632
gleason  0.432  -0.001 0.269  0.078  0.320  0.515   1.000 0.752
pgg45    0.434   0.051 0.276  0.078  0.458  0.632   0.752 1.000</code></pre>
</div>
</div>
<p>Based on the results of the correlation matrix we see that the strongest correlations are between lcavol and svi = 0.539, lcp and svi = 0.673, lcp and lcavol = 0.675 and gleason and pgg45 = 0.752. Therefore lcavol, svi, gleason, and lcp maybe covariates that are contributing to the possible and problematic colinearity we observed in 1a.</p>
</section>
<section id="c.-compute-the-variance-inflation-factors.-comment-on-whether-any-appear-problematic-and-why." class="level1">
<h1>1.C. Compute the variance inflation factors. Comment on whether any appear problematic and why.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(model)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lcavol  lweight      age     lbph      svi      lcp  gleason    pgg45 
2.054115 1.363704 1.323599 1.375534 1.956881 3.097954 2.473411 2.974361 </code></pre>
</div>
</div>
<p>All of the VIFs are under 10 which indicates that there is not significant mulitcolinearity that needs to be addressed. However, lcp, gleason, pgg45, and lcavol all have vif_values greater than 2 which means that the variables are moderately correlated. This is concerning as we saw that in part 1b, lcavol, gleason, and lcp also showed great correlation. As a result, this could be impacting the coefficents for this covariates.</p>
</section>
<section id="question-2-for-the-cars-dataset-fit-a-linear-model-with-distance-as-the-response-and-speed-as-the-predictor." class="level1">
<h1>Question 2: For the cars dataset, fit a linear model with distance as the response and speed as the predictor.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cars)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model_cars <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> speed, <span class="at">data =</span> cars)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dist ~ speed, data = cars)

Residuals:
    Min      1Q  Median      3Q     Max 
-29.069  -9.525  -2.272   9.215  43.201 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -17.5791     6.7584  -2.601   0.0123 *  
speed         3.9324     0.4155   9.464 1.49e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15.38 on 48 degrees of freedom
Multiple R-squared:  0.6511,    Adjusted R-squared:  0.6438 
F-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12</code></pre>
</div>
</div>
<ul>
<li><p>The intercept is B_0 = -17.5791, indicating that when all other predictors are at zero, distance is approximately -17.58. This is statistically significant as p = 0.0123.</p></li>
<li><p>The B_1 coefficient is 3.9324, indicating that for each unit increase in speed, distance increases by approximately 3.93. This is statistically significant as p = 1.49e-12.</p></li>
</ul>
</section>
<section id="a.-test-the-homoscedasticity-assumption-using-both-a-scatter-plot-between-the-residuals-and-fitted-values-and-an-f-test-of-equal-variance-below-and-above-the-fitted-value-of-30.-what-do-you-conclude-about-whether-the-assumption-is-met" class="level1">
<h1>2.A. Test the homoscedasticity assumption using both a scatter plot between the residuals and fitted values and an F-test of equal variance below and above the fitted value of 30. What do you conclude about whether the assumption is met?</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of residuals vs fitted values</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(model_cars), <span class="fu">residuals</span>(model_cars),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlab =</span> <span class="st">"Fitted values"</span>, <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">main =</span> <span class="st">"Residuals vs Fitted Values"</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="HW8_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># F-test for equal variance</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fitted_vals <span class="ot">&lt;-</span> <span class="fu">fitted</span>(model_cars)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>high_group <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model_cars)[fitted_vals <span class="sc">&gt;</span> <span class="dv">30</span>]</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>low_group <span class="ot">&lt;-</span> <span class="fu">residuals</span>(model_cars)[fitted_vals <span class="sc">&lt;=</span> <span class="dv">30</span>]</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(high_group, low_group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  high_group and low_group
F = 4.1325, num df = 34, denom df = 14, p-value = 0.006658
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 1.527594 9.415644
sample estimates:
ratio of variances 
          4.132502 </code></pre>
</div>
</div>
<p>Based on the plot it appears that there is an unequal distribution of residuals in the plot which could suggest the zero mean error assumption is violated.The F-test compares the variances of those with fitted values greater than 30 (high_group) and those with fitted values less than or equal to 30 (low_group). The p-value is less than 0.05, indicating that there is a significant difference between the variances of these groups. This suggests the presence of heteroscedasticity which would violate the zero mean error assumption.</p>
</section>
<section id="b.-report-the-estimate-of-the-heteroscedastic-consistent-variance-for-the-regression-slope." class="level1">
<h1>2.B. Report the estimate of the heteroscedastic consistent variance for the regression slope.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>coef_test <span class="ot">&lt;-</span> <span class="fu">coeftest</span>(model_cars, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(model_cars, <span class="at">type =</span> <span class="st">"HC0"</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>coef_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

             Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept) -17.57909    5.54187 -3.1720  0.002639 ** 
speed         3.93241    0.39868  9.8636 3.964e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>hetvar <span class="ot">&lt;-</span>model_cars <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vcovHC</span>() <span class="sc">%&gt;%</span> <span class="co"># calculate Heteroscedasticity-consistent estimation of the covariance matrix for coefficients</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">diag</span>() <span class="sc">%&gt;%</span> <span class="co"># gives variances as they are the diagonal of the covariance matrix</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>() <span class="co"># gives standard error as it is square root of variance</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>heteroscedastic_variance <span class="ot">&lt;-</span> hetvar[<span class="dv">2</span>]<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>heteroscedastic_variance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    speed 
0.1827881 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dist ~ speed, data = cars)

Residuals:
    Min      1Q  Median      3Q     Max 
-29.069  -9.525  -2.272   9.215  43.201 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -17.5791     6.7584  -2.601   0.0123 *  
speed         3.9324     0.4155   9.464 1.49e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15.38 on 48 degrees of freedom
Multiple R-squared:  0.6511,    Adjusted R-squared:  0.6438 
F-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12</code></pre>
</div>
</div>
<p>The estimate of the heteroscedastic consistent variance for the regression slope is 0.1827881.</p>
</section>
<section id="c.-construct-95-confidence-interval-of-the-regression-slope-assuming-homoscedasticity-and-using-the-results-in-2.b.-how-do-they-compare" class="level1">
<h1>2.C. Construct 95% confidence interval of the regression slope assuming homoscedasticity and using the results in 2.B. How do they compare?</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regular CI</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_cars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -31.167850 -3.990340
speed         3.096964  4.767853</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Robust CI</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>robust_se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model_cars, <span class="at">type =</span> <span class="st">"HC0"</span>)))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_cars)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>robust_ci <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> beta <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df =</span> <span class="fu">nrow</span>(cars)<span class="sc">-</span><span class="dv">2</span>) <span class="sc">*</span> robust_se,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> beta <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="fu">nrow</span>(cars)<span class="sc">-</span><span class="dv">2</span>) <span class="sc">*</span> robust_se</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>robust_ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 lower     upper
(Intercept) -28.721776 -6.436414
speed         3.130807  4.734010</code></pre>
</div>
</div>
<p>Regular CI: (3.096964, 4.767853). Robust CI: (3.130807, 4.734010)</p>
<p>While both intervals are fairly similar, the robust CI is slightly shifted as both the lower and upper bounds are higher. The robust CI is also more narrow, indicating that adjusting for heteroscedasticity reduces the uncertainty around the estimate.</p>
</section>
<section id="d.-check-for-the-lack-of-fit-of-the-model." class="level1">
<h1>2.D. Check for the lack of fit of the model.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating groups based on unique speed values</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>pure_error_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(dist <span class="sc">~</span> <span class="fu">factor</span>(speed), <span class="at">data =</span> cars)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_cars, pure_error_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: dist ~ speed
Model 2: dist ~ factor(speed)
  Res.Df     RSS Df Sum of Sq      F Pr(&gt;F)
1     48 11353.5                           
2     31  6764.8 17    4588.7 1.2369 0.2948</code></pre>
</div>
</div>
<p>The p-value is 0.2948 which indicates that pure_error_mode is not significantly better than model_cars. There is no lack of fit in model_cars, or the linear model.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>